index:
  - title: Abstract
    url: /pages/abstract.html
  - title: Introduction
    url: /pages/introduction.html
  #- title: Purpose
  #  url: /pages/purpose.html
  #- title: A Note on Context
  #  url: /pages/note-context.html
  #- title: Approach
  #  url: /pages/approach.html
  #- title: Eleven predictions on the influence of emerging technologies
  #  url: /pages/predictions-intro.html
  - title: Prediction 1
    header_title: Prediction
    before_title: 1
    url: /pages/predictions/prediction-1.html
  - title: Prediction 2
    header_title: Prediction
    before_title: 2
    url: /pages/predictions/prediction-2.html
  - title: Prediction 3
    header_title: Prediction
    before_title: 3
    url: /pages/predictions/prediction-3.html
  #- title: The Growing Impact of Identity Technologies on Citizen Engagement
  #  url: /pages/identity-technologies.html
  - title: Prediction 4
    header_title: Prediction
    before_title: 4
    url: /pages/predictions/prediction-4.html
  - title: Prediction 5
    header_title: Prediction
    before_title: 5
    url: /pages/predictions/prediction-5.html
  - title: Prediction 6
    header_title: Prediction
    before_title: 6
    url: /pages/predictions/prediction-6.html
  - title: Prediction 7
    header_title: Prediction
    before_title: 7
    url: /pages/predictions/prediction-7.html
  - title: Prediction 8
    header_title: Prediction
    before_title: 8
    url: /pages/predictions/prediction-8.html
  - title: Prediction 9
    header_title: Prediction
    before_title: 9
    url: /pages/predictions/prediction-9.html
  - title: Prediction 10
    header_title: Prediction
    before_title: 10
    url: /pages/predictions/prediction-10.html
  - title: Prediction 11
    header_title: Prediction
    before_title: 11
    url: /pages/predictions/prediction-11.html
  #- title: Enter blockchain technologies
  #  url: /pages/enter-blockchain.html
  - title: Implications
    url: /pages/implications-conclusions.html
  - title: Measure 1
    header_title: Measure
    before_title: 1
    url: /pages/measures/measure-1.html
  - title: Measure 2
    header_title: Measure
    before_title: 2
    url: /pages/measures/measure-2.html
  - title: Measure 3
    header_title: Measure
    before_title: 3
    url: /pages/measures/measure-3.html
  - title: Measure 4
    header_title: Measure
    before_title: 4
    url: /pages/measures/measure-4.html
  - title: Measure 5
    header_title: Measure
    before_title: 5
    url: /pages/measures/measure-5.html
  - title: Measure 6
    header_title: Measure
    before_title: 6
    url: /pages/measures/measure-6.html
  - title: Conclusion
    url: /pages/conclusion.html
  #- title: References
  #  url: /pages/references.html

small_index:
  - title: Abstract
    url: /pages/abstract.html
    single: true
  - title: Introduction
    url: /pages/introduction.html
    single: true
  - title: Prediction 1
    description: >
      The “fake news” arms race will grow further, shifting the focus of public debates.
    url: /pages/predictions/prediction-1.html
  - title: Prediction 2
    description: >
      “Social scores” will influence political and governmental responsiveness.
    url: /pages/predictions/prediction-2.html
  - title: Prediction 3
    description: >
      ID technologies will increase citizens’ pressure on decision makers.
    url: /pages/predictions/prediction-3.html
  - title: Prediction 4
    description: >
      More political parties will develop policy and choose candidates using digital platforms.
    url: /pages/predictions/prediction-4.html
  - title: Prediction 5
    description: >
      Different national regulation of social media will lead to increasingly different spaces for public debate.
    url: /pages/predictions/prediction-5.html
  - title: Prediction 6
    description: >
      Activists and tech companies will fight over who gets to speak to citizens.
    url: /pages/predictions/prediction-6.html
  - title: Prediction 7
    description: >
      “Free internet” will influence civic and political conversations.
    url: /pages/predictions/prediction-7.html
  - title: Prediction 8
    description: >
      Augmented reality may become a driver of increased citizen awareness.
    url: /pages/predictions/prediction-8.html
  - title: Prediction 9
    description: >
      Automation will reduce certain kinds of citizen feedback.
    url: /pages/predictions/prediction-9.html
  - title: Prediction 10
    description: >
      Bots will be used to acquire, mobilize, and coordinate activists.
    url: /pages/predictions/prediction-10.html
  - title: Prediction 11
    description: >
      Many will try to use ‘blockchain’ to raise trust in participative exercises.
    url: /pages/predictions/prediction-11.html
  - title: Implications
    url: /pages/implications-conclusions.html
    single: true
  - title: Measure 1
    description: >
      Governments should adopt user-centered digital practices.
    url: /pages/measures/measure-1.html
  - title: Measure 2
    description: >
      Set boundaries for the use of social scoring.
    url: /pages/measures/measure-2.html
  - title: Measure 3
    description: >
      Make use of citizens assemblies to set digital policies.
    url: /pages/measures/measure-3.html
  - title: Measure 4
    description: >
      When regulating tech companies, don’t forget to consider citizen engagement.
    url: /pages/measures/measure-4.html
  - title: Measure 5
    description: >
      Telecoms regulators need to consider citizen engagement.
    url: /pages/measures/measure-5.html
  - title: Measure 6
    description: >
      Design civic technologies for inclusiveness.
    url: /pages/measures/measure-6.html
  - title: Conclusion
    url: /pages/conclusion.html
    single: true